'use client';

import { useEffect, useMemo, useState } from 'react';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { BarChart3, CheckCircle2, ShieldCheck } from 'lucide-react';
import { api, Agent } from '@/lib/api';
import { performanceData } from '@/lib/mockData';

export default function Performance() {
  const [agents, setAgents] = useState<Agent[]>([]); const [error, setError] = useState('');
  useEffect(() => { api.agents().then(setAgents).catch((reason: Error) => setError(reason.message)); }, []);
  const active = agents.filter((agent) => agent.status === 'running'); const drafts = agents.reduce((sum, agent) => sum + Number(agent.metrics.drafts_created || 0), 0);
  const approvalRate = useMemo(() => { const values = agents.map((agent) => agent.metrics.human_approval_rate).filter((value): value is number => typeof value === 'number'); return values.length ? `${Math.round(values.reduce((sum, value) => sum + value, 0) / values.length)}%` : '—'; }, [agents]);
  return <div className="max-w-7xl mx-auto space-y-7"><div><div className="flex items-center gap-2 text-sm text-cyan-300"><ShieldCheck size={16} /> Measure before expanding</div><h1 className="mt-2 text-3xl font-bold">Pilot performance</h1><p className="mt-1 text-slate-400">This panel tracks human-reviewed draft activity. External actions stay at zero by design.</p></div>{error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-200">{error}</div>}<div className="grid gap-5 md:grid-cols-3"><Metric label="Approved draft agents" value={active.length} note="Draft-only mode" /><Metric label="Drafts created" value={drafts} note="All require review" /><Metric label="Human approval rate" value={approvalRate} note="Collected once reviewers respond" /></div><section className="glass-card rounded-2xl p-6"><div className="flex items-center gap-2"><BarChart3 className="text-cyan-300" size={20} /><h2 className="text-xl font-semibold">Illustrative pilot trend</h2></div><p className="mt-1 text-sm text-slate-400">Replace this deterministic sandbox baseline with a live metrics stream once reviewed drafts exist.</p><div className="mt-6 h-[310px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={performanceData}><CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} /><XAxis dataKey="date" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} /><YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} /><Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155', borderRadius: 8 }} /><Legend /><Line type="monotone" dataKey="drafts" name="Drafts routed" stroke="#22d3ee" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="reviews" name="Human reviews" stroke="#a78bfa" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></section><section className="glass-card rounded-2xl overflow-hidden"><div className="border-b border-slate-800 p-6"><h2 className="text-xl font-semibold">Agent safety ledger</h2></div><div className="divide-y divide-slate-800">{agents.length ? agents.map((agent) => <div className="flex items-center justify-between p-5" key={agent.id}><div><p className="font-medium">{agent.name}</p><p className="mt-1 text-sm text-slate-400">{agent.metrics.drafts_created || 0} drafts · {agent.metrics.external_actions || 0} external actions</p></div><div className="flex items-center gap-2 text-sm text-green-300"><CheckCircle2 size={16} /> Draft-only policy</div></div>) : <p className="p-6 text-slate-400">No pilot agents yet. Create a limited draft pilot from the Deploy page.</p>}</div></section></div>;
}
function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className="glass-card rounded-2xl p-6"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-4xl font-bold">{value}</p><p className="mt-2 text-sm text-cyan-200">{note}</p></div>; }
