#!/usr/bin/env python3
"""Export a deployed agent as a runnable LangGraph bundle (zip).

    PYTHONPATH=. python scripts/export_agent_bundle.py <agent_id> \
        --out runs/bundles/<agent_id>.zip

The bundle contains:
- graph.py          the generated, compile-checked LangGraph workflow
- langgraph.json    LangGraph Studio / `langgraph dev` config
- README.md         run instructions + langchain-mcp-adapters bridge snippet

Execute it with the optional agents extra:
    pip install -r requirements-agents.txt
"""

from __future__ import annotations

import argparse
import asyncio
import io
import json
import os
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

README_TEMPLATE = """# {agent_name}

Generated by AutoPilot FDE from discovered process `{process_id}`.

## Run locally (LangGraph Studio / dev server)

```bash
pip install -r {agents_requirements}
langgraph dev          # opens Studio; graph id: "agent"
```

## Execute headlessly

```python
import os
os.environ.setdefault("AUTOPILOT_CHECKPOINT_DB", "checkpoints.sqlite")
import graph
result = graph.app.invoke(
    {{"case_id": "case-1", "payload": {{}}, "step_history": []}},
    config={{"configurable": {{"thread_id": "thread-1"}}}},
)
# At an approval gate the invoke returns with __interrupt__; approve and resume:
from langgraph.types import Command
result = graph.app.invoke(
    Command(resume={{"approved": True, "actor": "you"}}),
    config={{"configurable": {{"thread_id": "thread-1"}}}},
)
```

## Use the AutoPilot MCP tools inside any LangGraph agent

```python
pip install langchain-mcp-adapters
```

```python
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain.agents import create_agent

client = MultiServerMCPClient({{
    "autopilot": {{
        "url": "{mcp_url}",
        "transport": "http",
    }},
}})
tools = await client.get_tools()   # dashboard_summary, simulate_process, ...
agent = create_agent("openai:gpt-4.1", tools)
```

## Safety contract

- Approval gates are native `interrupt()` checkpoints; nothing external is
  sent without a human decision recorded in the audit trail.
- EXTERNAL_WRITE / CRITICAL_TRANSACTION steps raise StructuralGateError —
  they are structurally non-automatable.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("agent_id")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    if override := os.getenv("AUTOPILOT_DB_PATH", "").strip():
        import backend.database as database

        database.DB_PATH = Path(override).expanduser()

    async def load():
        await database.init_db()
        try:
            return await database.get_agent(args.agent_id)
        finally:
            await database.close_db()

    import backend.database as database  # noqa: F401 - DB path set above

    agent = asyncio.run(load())
    if not agent or not agent.generated_code:
        print(f"Agent not found or has no generated code: {args.agent_id}",
              file=sys.stderr)
        return 1

    generated = agent.generated_code
    out = Path(args.out).expanduser() if args.out else (
        Path.cwd() / "runs" / "bundles" / f"{args.agent_id}.zip"
    )
    out.parent.mkdir(parents=True, exist_ok=True)

    mcp_url = os.getenv("AUTOPILOT_MCP_URL", "http://localhost:8000/mcp")
    readme = README_TEMPLATE.format(
        agent_name=generated.agent_name,
        process_id=generated.process_id,
        agents_requirements="requirements-agents.txt",
        mcp_url=mcp_url,
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as bundle:
        bundle.writestr("graph.py", generated.python_code)
        bundle.writestr("langgraph.json", json.dumps(generated.langgraph_json, indent=2))
        bundle.writestr("requirements-agents.txt",
                        (Path(__file__).resolve().parents[1] /
                         "requirements-agents.txt").read_text())
        bundle.writestr("README.md", readme)
    out.write_bytes(buffer.getvalue())
    print(f"Wrote bundle for '{generated.agent_name}' -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
