'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { CheckCircle2, Database, LockKeyhole, MessageSquare, MessagesSquare, ShieldCheck } from 'lucide-react';
import { api, Channel } from '@/lib/api';

export default function Channels() {
  const [channels, setChannels] = useState<Channel[]>([]); const [error, setError] = useState('');
  useEffect(() => { api.channels().then(setChannels).catch((reason: Error) => setError(reason.message)); }, []);
  return <div className="max-w-6xl mx-auto space-y-8"><div><div className="flex items-center gap-2 text-sm text-cyan-300"><ShieldCheck size={16} /> Slack-first integration</div><h1 className="mt-2 text-3xl font-bold">Observation sources</h1><p className="mt-1 text-slate-400">The MVP has no write scopes and ingests only channel messages and thread relationships.</p></div>{error && <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-200">{error}</div>}<div className="grid gap-6 md:grid-cols-2">{channels.map((channel) => <div key={channel.id} className="glass-card rounded-2xl p-6"><div className="flex items-start justify-between"><div className="rounded-xl bg-purple-500/10 p-3 text-purple-300"><MessagesSquare size={26} /></div><div className="flex items-center gap-2 rounded-full border border-green-400/30 bg-green-400/10 px-2.5 py-1 text-xs text-green-200"><CheckCircle2 size={13} /> Read-only active</div></div><h2 className="mt-6 text-xl font-semibold">{channel.name}</h2><p className="mt-2 text-sm text-slate-400">{channel.message_count} observations available for discovery</p><div className="mt-6 grid grid-cols-2 gap-3"><Mini icon={<LockKeyhole size={15} />} label="Scope" value="Read-only" /><Mini icon={<Database size={15} />} label="Case key" value="Slack thread" /></div></div>)}{!channels.length && !error && <div className="glass-card rounded-2xl p-6 text-slate-400">Loading channel information…</div>}<div className="rounded-2xl border border-dashed border-slate-700 bg-slate-900/30 p-6"><MessageSquare className="text-slate-500" /><h2 className="mt-5 text-xl font-semibold text-slate-200">Next integrations</h2><p className="mt-2 text-sm text-slate-400">Shared inbox and CRM connectors are intentionally deferred until the Slack evidence and approval workflow are validated.</p><div className="mt-5 flex flex-wrap gap-2">{['Shared Gmail / Outlook', 'CRM webhooks', 'Call transcripts'].map((item) => <span key={item} className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-500">{item}</span>)}</div></div></div><section className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-6"><h2 className="font-semibold text-cyan-100">Data handling boundary</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Source messages are read-only. Discovery retains source IDs and evidence snippets so a reviewer can challenge each inferred activity. Agents do not receive Slack write permissions in this MVP.</p></section></div>;
}
function Mini({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-lg bg-slate-900/70 p-3"><div className="flex items-center gap-1.5 text-xs text-slate-500">{icon}{label}</div><p className="mt-1 text-sm font-medium">{value}</p></div>; }
